# Generated by Django 4.0.1 on 2022-01-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_newuser_session_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='session_token',
        ),
    ]
