# Generated by Django 4.0.2 on 2022-02-12 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetanalysis',
            old_name='sentimet_data',
            new_name='sentiment_data',
        ),
    ]
