# Generated by Django 4.0.2 on 2022-02-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tweetanalysis_hour_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetanalysis',
            name='product_name',
            field=models.TextField(null=True),
        ),
    ]
