# Generated by Django 4.0.2 on 2022-02-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tweetanalysis_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetanalysis',
            name='fetched_date',
            field=models.DateField(null=True),
        ),
    ]
